  
name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Buid Env
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
    - name: Update Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Clone Config
      run: |
        wget https://raw.githubusercontent.com/breakersun/build-lede/master/.config
    - name: Build
      run: |
        make -j4
        
    - name: Release/Publish BIN
      uses: skx/github-action-publish-binaries@release-1.2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        args: './bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz'
