name: lede

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
    - name: Clone source
      run: |
        cd /home/runner
        git clone https://github.com/breakersun/lede.git
        sudo chmod -R 777 lede
        sudo chown -R runner:runner lede
        cd /home/runner/lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Clone config
      run: |
        cd /home/runner/lede/
        wget https://raw.githubusercontent.com/breakersun/build-lede/master/.config
    - name: Build
      run: |
        cd /home/runner/lede
        make -j2
    - name: Commit to docker-repo
      run: |
        cd /home/runner
        git clone https://github.com/breakersun/docker-openwrt.git
        cp /home/runner/lede/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz /home/runner/docker-openwrt/
        cd /home/runner/docker-openwrt/
        git config --local user.email "leosunsl@outlook.com"
        git config --local user.name "action"
        git commit -m "bump changes from source" -a
    - name: Push to docker-repo
      uses: ad-m/github-push-action@master
      with:
        directory: '/home/runner/docker-openwrt/'
        github_token: ${{ secrets.MY_TOKEN }}
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/lede/bin
